version: '3.8'

services:
  app:
    build: .
    container_name: task-manager-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_USER=postgres
      - DB_PASSWORD=P@ssw0rd
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=taskdb
    depends_on:
      - db
    restart: always

  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: taskdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    #ports:
    #  - "5432:5432"
    restart: always

volumes:
  pgdata:
